# Generated by Django 3.2 on 2023-03-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfermodel',
            old_name='liters',
            new_name='fuel_liters',
        ),
        migrations.RenameField(
            model_name='transfermodel',
            old_name='pump',
            new_name='fuel_pump',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_date_estimated',
            field=models.DateField(blank=True, help_text='Fecha de entrega estimada de la orden', null=True, verbose_name='Fecha de entrega estimada'),
        ),
    ]
