# Generated by Django 3.2 on 2023-03-18 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_vehiclemodel_responsible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20230316_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('estatus', models.PositiveSmallIntegerField(choices=[(1, 'Remisión (Ingreso)'), (2, 'Autorización y asignación de camión'), (3, 'Cáptura de salida'), (4, 'Salida del almacén'), (5, 'Entregado'), (6, 'Entrada a almacén'), (7, 'Cáptura de entrada'), (8, 'Finalizado')], default=1)),
                ('api_gps', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transfermodel',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='transfermodel',
            name='fuel_pump',
        ),
        migrations.RemoveField(
            model_name='transfermodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transfermodel',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='transfermodel',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='transfermodel',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='driver',
            field=models.ForeignKey(help_text='Conductor que realizará el traslado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_transfer', to=settings.AUTH_USER_MODEL, verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='fuel_liters',
            field=models.FloatField(blank=True, default=0, help_text='Litros de combustible que se utilizaron en el traslado', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Litros de combustible'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='fuel_pump',
            field=models.ForeignKey(blank=True, help_text='Bombas de combustible que se utilizará', null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.fuelpumpmodel', verbose_name='Bombas de combustible que se utilizará'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehículo que se utilizará para el traslado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='administration.vehiclemodel', verbose_name='Vehículo'),
        ),
        migrations.DeleteModel(
            name='LogTrasnferModel',
        ),
        migrations.DeleteModel(
            name='TransferModel',
        ),
        migrations.AddField(
            model_name='logordermodel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel'),
        ),
        migrations.AddField(
            model_name='logordermodel',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logordermodel_user_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logordermodel',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logordermodel_user_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
