# Generated by Django 3.2 on 2023-03-18 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_vehiclemodel_responsible'),
        ('orders', '0003_auto_20230318_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailordermodel',
            name='quantity_transfer',
            field=models.FloatField(blank=True, default=0, help_text='Cantidad a trasladar', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad a trasladar'),
        ),
        migrations.AlterField(
            model_name='detailordermodel',
            name='truck',
            field=models.ForeignKey(blank=True, help_text='Remolque que se utilizará en el traslado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='truck_detail_transfer', to='administration.truckvehiclemodel', verbose_name='Remolque que se utilizará'),
        ),
    ]
