# Generated by Django 3.2 on 2023-03-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_vehiclemodel_responsible'),
        ('orders', '0004_auto_20230318_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logordermodel',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remisión (Ingreso)'), (2, 'Autorización y asignación de camión'), (3, 'Cáptura de salida'), (4, 'Salida del almacén'), (5, 'Entregando'), (6, 'Entregado'), (7, 'Entrada a almacén'), (8, 'Cáptura de entrada'), (9, 'Finalizado')], default=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='driver',
            field=models.ForeignKey(help_text='Conductor que realizará el traslado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_transfer', to='administration.drivermodel', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='key_order',
            field=models.IntegerField(help_text='Folio de la orden', unique=True, verbose_name='Folio de la orden'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remisión (Ingreso)'), (2, 'Autorización y asignación de camión'), (3, 'Cáptura de salida'), (4, 'Salida del almacén'), (5, 'Entregando'), (6, 'Entregado'), (7, 'Entrada a almacén'), (8, 'Cáptura de entrada'), (9, 'Finalizado')], default=1, help_text='Estatus del pedido', verbose_name='Estatus del pedido'),
        ),
    ]
