# Generated by Django 2.2.13 on 2021-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_pedido_indentificador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='indentificador_estado',
            field=models.CharField(default='2', max_length=20),
        ),
    ]
