# Generated by Django 2.2.13 on 2021-08-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20210820_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='UniMed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.UnidadMedida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='autpor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Autoriza'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Proceso'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Equipo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Proceso'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.UnidadMedida'),
        ),
    ]
