# Generated by Django 2.2.13 on 2021-10-11 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20211001_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='proceso',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
