# Generated by Django 2.2.13 on 2021-08-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_pedido_fecha_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio_uni',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='preciotransaccion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
