# Generated by Django 2.2.13 on 2021-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_pedido_divisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status2',
            field=models.CharField(default='Prox', max_length=20),
        ),
    ]
