# Generated by Django 2.2.13 on 2021-10-28 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20211028_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(default='eliminar default', help_text='Apellido Materno', max_length=15),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='eliminar default', help_text='Apellido Paterno', max_length=15),
        ),
        migrations.AddField(
            model_name='empleado',
            name='clabe_banco',
            field=models.IntegerField(default=999999999999999999, unique=True, validators=[django.core.validators.MinValueValidator(111111111111111111), django.core.validators.MaxValueValidator(999999999999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(default='eliminar default', help_text='Nombre de la persona de emergencia', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuenta',
            field=models.IntegerField(default=99, unique=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(default=99, help_text='Edad', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(default='oscar@mercax.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(default=99, help_text='Numero de seguro social', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(default=99, help_text='Registro Federal de Contribuyente', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_celular',
            field=models.IntegerField(default=4427744366, help_text='telefono celular a 10 digitos', unique=True, validators=[django.core.validators.MinValueValidator(1111111111), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_emergencia',
            field=models.IntegerField(default=4427744366, help_text='Telefono de emergencia confirmar', validators=[django.core.validators.MinValueValidator(1111111111), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_fijo',
            field=models.IntegerField(default=4427744366, help_text='telefono a 10 digitos', validators=[django.core.validators.MinValueValidator(1111111111), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(help_text='Nombre', max_length=15),
        ),
    ]
