# Generated by Django 2.2.13 on 2021-09-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0010_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='licenciacaduca',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Tipo de computadora', max_length=100)),
                ('cpu', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('almacenamiento', models.CharField(max_length=20)),
                ('tipoAl', models.CharField(max_length=3)),
                ('macEth', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('macWifi', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('serie', models.CharField(max_length=40, unique=True)),
                ('asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Empleado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Computadoras',
            },
        ),
    ]
