# Generated by Django 2.2.13 on 2021-09-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0011_auto_20210908_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Tipo de computadora', max_length=100)),
                ('tipo', models.CharField(help_text='Tipo de computadora', max_length=100)),
                ('motivo', models.CharField(help_text='Tipo de computadora', max_length=100)),
                ('serie', models.CharField(max_length=40, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Empleado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Herramientas',
            },
        ),
    ]
