# Generated by Django 2.2.13 on 2021-09-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_auto_20210908_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='motivo_de_edicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
