# Generated by Django 2.2.13 on 2021-09-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0016_auto_20210924_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='articulo',
            field=models.CharField(max_length=50),
        ),
    ]
