# Generated by Django 2.2.13 on 2021-09-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0022_auto_20210927_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='X-Revisar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status2',
            field=models.CharField(default='Proximo', max_length=20),
        ),
    ]
