# Generated by Django 2.2.13 on 2021-09-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0023_auto_20210927_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='proceso',
            field=models.CharField(max_length=15),
        ),
    ]
