# Generated by Django 2.2.13 on 2021-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0024_auto_20210929_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='proceso',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
