# Generated by Django 2.2.13 on 2021-10-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0025_auto_20211001_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='proceso',
            field=models.CharField(default='sinproceso', max_length=15),
        ),
    ]
