# Generated by Django 2.2.13 on 2021-10-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0026_auto_20211002_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='proceso',
            field=models.CharField(max_length=15),
        ),
    ]
