# Generated by Django 2.2.13 on 2021-10-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0028_pedido_divisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status2',
            field=models.CharField(default='Prox', max_length=20),
        ),
    ]
