# Generated by Django 2.2.13 on 2021-11-11 01:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0031_auto_20211103_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(default='agregar', max_length=15),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='agregar', max_length=15),
        ),
        migrations.AddField(
            model_name='empleado',
            name='clabe_banco',
            field=models.BigIntegerField(default=999999999999999998, unique=True, validators=[django.core.validators.MinValueValidator(111111111111111111), django.core.validators.MaxValueValidator(999999999999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(default='eliminar default', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuenta',
            field=models.BigIntegerField(default=1000000001, unique=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(default='oscar@mercax.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nominaBanco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.Banco'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(default=99, max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.Puesto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(default=99, max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_celular',
            field=models.BigIntegerField(default=4427744366, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_emergencia',
            field=models.BigIntegerField(default=4427744366, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_fijo',
            field=models.BigIntegerField(default=4427744366, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
