# Generated by Django 2.2.13 on 2022-01-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0033_auto_20211110_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='iva',
            field=models.FloatField(default=0.16),
        ),
    ]
