# Generated by Django 2.2.13 on 2022-02-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0034_pedido_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
