# Generated by Django 2.2.13 on 2022-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0035_auto_20220202_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccionentrega',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccionfiscal',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razonsocial',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
