# Generated by Django 2.2.13 on 2022-02-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0036_auto_20220203_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(help_text='Comodin interno', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccionentrega',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccionfiscal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razonsocial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
