# Generated by Django 2.2.13 on 2022-02-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0037_auto_20220203_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
