# Generated by Django 2.2.13 on 2022-02-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0039_empresa_rfcempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='urllogoempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
