# Generated by Django 2.2.13 on 2022-05-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0044_auto_20220518_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombresrelacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
