# Generated by Django 2.2.13 on 2022-05-18 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0048_auto_20220518_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='artciulosestandarizados',
            name='fecha2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artciulosestandarizados',
            name='fecha3',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artciulosestandarizados',
            name='fecha4',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artciulosestandarizados',
            name='fechapreciosugerido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artciulosestandarizados',
            name='precio2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artciulosestandarizados',
            name='precio3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artciulosestandarizados',
            name='precio4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='artciulosestandarizados',
            name='preciosugerido',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nombresrelacion',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Artciulosestandarizados'),
        ),
    ]
