# Generated by Django 2.2.13 on 2022-05-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0049_auto_20220518_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artciulosestandarizados',
            name='fecha2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artciulosestandarizados',
            name='fecha3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artciulosestandarizados',
            name='fecha4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nombresrelacion',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Artciulosestandarizados'),
        ),
    ]
