# Generated by Django 2.2.13 on 2022-05-25 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0050_auto_20220519_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='clabe_banco',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(99999999999999999), django.core.validators.MaxValueValidator(999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='nombresrelacion',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Artciulosestandarizados'),
        ),
    ]
