# Generated by Django 2.2.13 on 2022-06-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0053_auto_20220602_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='recibidos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nombresrelacion',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Artciulosestandarizados'),
        ),
    ]
