# Generated by Django 2.2.13 on 2022-06-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0055_auto_20220622_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='recurrente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nombresrelacion',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Artciulosestandarizados'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estandarizadoprodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Artciulosestandarizados'),
        ),
    ]
