# Generated by Django 2.2.13 on 2021-12-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0033_auto_20211110_1928'),
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasdet',
            name='producto',
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Pedido'),
        ),
    ]
