# Generated by Django 3.2 on 2024-01-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='regimen',
            field=models.CharField(choices=[('Revisar datos del proveedor', 'Revisar datos del proveedor'), ('Persona moral', 'Persona moral'), ('Régimen Simplificado de Confianza', 'Régimen Simplificado de Confianza'), ('Sueldos y salarios e ingresos asimilados a salarios', 'Sueldos y salarios e ingresos asimilados a salarios'), ('Régimen de Actividades Empresariales y Profesionales', 'Régimen de Actividades Empresariales y Profesionales'), ('Régimen de Incorporación Fiscal', 'Régimen de Incorporación Fiscal'), ('Enajenación de bienes', 'Enajenación de bienes'), ('Régimen de Actividades Empresariales con ingresos a través de Plataformas Tecnológicas', 'Régimen de Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('Régimen de Arrendamiento', 'Régimen de Arrendamiento'), ('Intereses', 'Intereses'), ('Obtención de premios', 'Obtención de premios'), ('Dividendos', 'Dividendos'), ('Demás ingresos', 'Demás ingresos'), ('Régimen Simplificado de Confianza', 'Régimen Simplificado de Confianza'), ('Régimen de Actividades Empresariales con ingresos a través de Plataformas Tecnológicas', 'Régimen de Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('Régimen de Arrendamiento', 'Régimen de Arrendamiento'), ('Régimen de Actividades Empresariales y Profesionales', 'Régimen de Actividades Empresariales y Profesionales')], default='Revisar datos del proveedor', max_length=86),
        ),
    ]
