# Generated by Django 3.2 on 2024-01-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='regimen',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Revisar datos del proveedor'), (2, 'Persona moral'), (3, 'Régimen Simplificado de Confianza'), (4, 'Sueldos y salarios e ingresos asimilados a salarios'), (5, 'Régimen de Actividades Empresariales y Profesionales'), (6, 'Régimen de Incorporación Fiscal'), (7, 'Enajenación de bienes'), (8, 'Régimen de Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), (9, 'Régimen de Arrendamiento'), (10, 'Intereses'), (11, 'Obtención de premios'), (12, 'Dividendos'), (13, 'Demás ingresos'), (14, 'Régimen Simplificado de Confianza'), (15, 'Régimen de Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), (16, 'Régimen de Arrendamiento'), (17, 'Régimen de Actividades Empresariales y Profesionales')], default=1),
        ),
    ]
