# Generated by Django 2.2.13 on 2022-01-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_auto_20211225_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='no_factura',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
