# Generated by Django 2.2.13 on 2022-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_comprasenc_autorizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='autorizacion',
            field=models.CharField(default='Autorización: Pendiente', max_length=50),
        ),
    ]
