# Generated by Django 2.2.13 on 2022-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_auto_20220127_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasdet',
            name='descuento',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
