# Generated by Django 2.2.13 on 2022-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0004_auto_20220918_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='autorizacion',
            field=models.CharField(default='OC: Autorización Pendiente', max_length=50),
        ),
    ]
