# Generated by Django 2.2.13 on 2022-02-02 05:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0034_pedido_iva'),
        ('cmp', '0004_auto_20220129_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='bancoproveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Banco'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='clabeproveedor',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000000000000), django.core.validators.MaxValueValidator(999999999999999999)]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuentabanco',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfcproveedor',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
