# Generated by Django 2.2.13 on 2022-02-02 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0005_auto_20220201_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='clabeproveedor',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(2000000000000000), django.core.validators.MaxValueValidator(999999999999999999)]),
        ),
    ]
