# Generated by Django 2.2.13 on 2022-02-02 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0006_auto_20220201_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuentabanco',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
