# Generated by Django 2.2.13 on 2022-02-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0034_pedido_iva'),
        ('cmp', '0007_auto_20220201_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='empresaoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.Empresa'),
        ),
    ]
