# Generated by Django 2.2.13 on 2022-10-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0007_auto_20221017_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='autorizante',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
