# Generated by Django 2.2.13 on 2022-02-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0009_auto_20220202_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='empresaoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Empresa'),
        ),
    ]
