# Generated by Django 2.2.13 on 2022-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0010_auto_20220202_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasdet',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
