# Generated by Django 2.2.13 on 2022-02-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0011_auto_20220203_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='diascredito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
