# Generated by Django 2.2.13 on 2022-02-03 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0012_auto_20220203_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuentabanco',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
