# Generated by Django 2.2.13 on 2022-02-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0015_cfdi_pagotipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagotipo',
            name='uc',
        ),
        migrations.DeleteModel(
            name='Cfdi',
        ),
        migrations.DeleteModel(
            name='Pagotipo',
        ),
    ]
