# Generated by Django 2.2.13 on 2022-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0017_auto_20220209_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='giro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombrecomercial',
            field=models.CharField(default='Falta Nombre Comerical', max_length=70),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='clabeproveedor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfcproveedor',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
