# Generated by Django 2.2.13 on 2022-02-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0018_auto_20220210_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='clabeproveedor',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombrecomercial',
            field=models.CharField(max_length=70),
        ),
    ]
