# Generated by Django 2.2.13 on 2022-02-16 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmp', '0020_clavessat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClavesSat',
            new_name='usofactura',
        ),
    ]
