# Generated by Django 2.2.13 on 2022-02-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0021_auto_20220215_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usofactura',
            old_name='clavesat',
            new_name='uso_factura',
        ),
    ]
