# Generated by Django 2.2.13 on 2022-02-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0023_auto_20220216_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usofactura',
            options={'verbose_name_plural': 'Usos Facturas'},
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='no_factura',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmp.UsoFactura'),
        ),
    ]
