#!/bin/bash

NAME="firefly"
VIRTUALENV="/home/firefly/v1/.venv/"
DJANGODIR="/home/firefly/v1/"
USER=firefly
GROUP=sudo
NUM_WORKERS=3
DJANGO_WSGI_MODULE=app.wsgi

echo "Starting $NAME as `whoami`"

cd $VIRTUALENV
source bin/activate
cd $DJANGODIR

export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec gunicorn ${DJANGO_WSGI_MODULE} \
        --workers $NUM_WORKERS \
        --user=$USER --group=$GROUP \
        --log-level=debug \
        --bind=127.0.0.1:8000
