# Generated by Django 3.0.7 on 2023-02-24 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BombaDiesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='descripción')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='Nombre común o comercial')),
                ('razonSocial', models.CharField(max_length=120, unique=True, verbose_name='Razón Social')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('nombreContacto', models.CharField(max_length=20, verbose_name='Nombre del contacto')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.PositiveIntegerField()),
                ('diasCredito', models.PositiveIntegerField(verbose_name='Dias de credito')),
                ('credito', models.FloatField(default=0.0, verbose_name='Credito Autorizado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoRepublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='Nombre del Estado de la Republica')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LugarEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='Nombre común')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero de la calle')),
                ('calle', models.CharField(max_length=10, verbose_name='Calle')),
                ('colonia', models.CharField(max_length=10, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=10, verbose_name='Municipio')),
                ('codigoPostal', models.PositiveIntegerField(verbose_name='Codigo Postal')),
                ('EstadoRepublica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.EstadoRepublica')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.ClienteC', verbose_name='Razon Social')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('claveunica', models.CharField(max_length=150, unique=True, verbose_name='identificador Aleatorio')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cantidad en Toneladas')),
                ('fEntrega', models.DateField()),
                ('estadoRef', models.CharField(default='Capturado', max_length=20, verbose_name='Estado de pedido')),
                ('facturado', models.BooleanField()),
                ('timbre', models.CharField(default='No timbrado', max_length=20, verbose_name='Verificador de timbrado')),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='Nombre del Estado de la Republica')),
                ('lEntrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.LugarEntrega', verbose_name='Lugar de entrega')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrasladoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='descripción')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fEntrega', models.DateField(blank=True, null=True)),
                ('fRegreso', models.DateField(blank=True, null=True)),
                ('kmtoma', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje inicial')),
                ('kmentrega', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje de entrega')),
                ('kmfinal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje final')),
                ('ubitoma', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ubicacion inicial')),
                ('ubientrega', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ubicacion de entrega')),
                ('ubifinal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ubicacion final')),
                ('tonelajeDeclarado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Tonelaje declarado')),
                ('tonelajeEntregado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Tonelaje entregado')),
                ('litrosRecarga', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Litros de recarga')),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.BombaDiesel', verbose_name='Bomba de diesel')),
                ('pedidoClave', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='comercial.Pedidos', verbose_name='Clave del pedido')),
                ('trasladoTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.TrasladoTipo', verbose_name='Tipo de traslado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='descripción')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='descripción')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pedidos',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.Presentacion', verbose_name='Tipo de empaque'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.ProductoC', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
