# Generated by Django 2.2.13 on 2022-07-08 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmp', '0001_initial'),
        ('inv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='RH, Proveedor, etc', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperadorPesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombres y Apellidos', max_length=50, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Operadores de camiones pesados',
            },
        ),
        migrations.CreateModel(
            name='SolicitantesUtilitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombres y Apellidos', max_length=50, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Autorizados para pedir utilitarios',
            },
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('visitaa', models.CharField(max_length=50)),
                ('placas', models.CharField(help_text='placas sin guiones', max_length=7, unique=True)),
                ('temperatura', models.FloatField()),
                ('horasalida', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.MotivoVisita')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Si es proveedor, selecciona aquí', null=True, on_delete=django.db.models.deletion.PROTECT, to='cmp.Proveedor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehiculoPesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numeroeconomico', models.CharField(help_text='Numero de la unidad de Vehiculo', max_length=5, unique=True)),
                ('placas', models.CharField(help_text='placas sin guiones', max_length=7, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos Pesados',
            },
        ),
        migrations.CreateModel(
            name='VehiculoLigero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numeroeconomico', models.CharField(help_text='Numero de la unidad de Vehiculo', max_length=5, unique=True)),
                ('placas', models.CharField(help_text='placas sin guiones', max_length=7, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.SolicitantesUtilitario')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos Ligeros',
            },
        ),
        migrations.CreateModel(
            name='TanquesDiesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Banco, Patio, Planta, ETC.', max_length=50, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tanques de Diesel',
            },
        ),
        migrations.CreateModel(
            name='ReciboEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('movimiento', models.CharField(help_text='recibo o entrega', max_length=7)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recibo o entrega',
            },
        ),
        migrations.CreateModel(
            name='MotivoIngresoUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=20)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Motivos de ingresos',
            },
        ),
        migrations.CreateModel(
            name='LlavesEnResguardo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('golpes', models.BooleanField(default=False, help_text='¿Gopes nuevos?')),
                ('tarjeta', models.BooleanField(default=True, help_text='Tarjeta de circulación')),
                ('poliza', models.BooleanField(default=True, help_text='Poliza de seguro')),
                ('notas', models.CharField(blank=True, max_length=300, null=True)),
                ('involucrado', models.ForeignKey(help_text='Nombre de quien se recibe o entrega las llaves', on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.ReciboEntrega')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado')),
            ],
            options={
                'verbose_name_plural': 'Llaves en resguardo',
            },
        ),
        migrations.CreateModel(
            name='IngresoUnidadPesada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fsalida', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.MotivoIngresoUnidad')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.TanquesDiesel')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado')),
            ],
            options={
                'verbose_name_plural': 'Ingresos de unidades pesadas',
            },
        ),
        migrations.CreateModel(
            name='DestinosClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre Sucursal', max_length=50, unique=True)),
                ('razonsocial', models.CharField(blank=True, max_length=200, null=True)),
                ('direccionfiscal', models.CharField(blank=True, max_length=200, null=True)),
                ('direccionentrega', models.CharField(blank=True, max_length=200, null=True)),
                ('rfcempresa', models.CharField(blank=True, max_length=13, null=True)),
                ('horarios', models.CharField(blank=True, max_length=100, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DescargaDeDiesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('residual', models.FloatField(blank=True, null=True)),
                ('litrosenbomba', models.FloatField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inv.Pedido')),
                ('tanquedediesel', models.ForeignKey(help_text='en donde se descarga?', on_delete=django.db.models.deletion.PROTECT, to='bita.TanquesDiesel')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargaDeUrea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('litros', models.FloatField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargaDeDiesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('litros', models.FloatField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.DestinosClientes')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
