# Generated by Django 2.2.13 on 2022-04-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0043_auto_20220226_0002'),
        ('bita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(default='¿sin descripción?', help_text='descripción', max_length=15),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='empresad',
            field=models.ForeignKey(blank=True, help_text='¿A que empresa pertenece?', null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Empresa'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='¿sin marca?', help_text='marca comercial', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(default='¿Sin Modelo?', help_text='modelo/año', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placas',
            field=models.CharField(default='UKE258A', help_text='numero de placas sin guiones', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numeroeconomico',
            field=models.CharField(default='¿Numero?', help_text='numero economico', max_length=8, unique=True),
        ),
    ]
