# Generated by Django 2.2.13 on 2022-04-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bita', '0002_auto_20220416_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nombre del responsable', max_length=20, null=True),
        ),
    ]
