# Generated by Django 2.2.13 on 2022-04-21 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0050_auto_20220421_2358'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0043_auto_20220226_0002'),
        ('bita', '0004_autorizadoutilitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDeDiesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('litros', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargaDeUrea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('litros', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DescargaDeDiesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Pedido')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinosClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre_Empresa-Dirección_Corta en caso de tener mas de un domicilio la misma empresa', max_length=50, unique=True)),
                ('razonsocial', models.CharField(blank=True, max_length=200, null=True)),
                ('direccionfiscal', models.CharField(blank=True, max_length=200, null=True)),
                ('direccionentrega', models.CharField(blank=True, max_length=200, null=True)),
                ('rfcempresa', models.CharField(blank=True, max_length=13, null=True)),
                ('horarios', models.CharField(blank=True, max_length=100, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngresoUnidadPesada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fsalida', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Ingresos de unidades pesadas',
            },
        ),
        migrations.CreateModel(
            name='LlavesEnResguardo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('golpes', models.BooleanField(default=False, help_text='¿Gopes nuevos?')),
                ('tarjeta', models.BooleanField(default=True, help_text='Tarjeta de circulación')),
                ('poliza', models.BooleanField(default=True, help_text='Poliza de seguro')),
                ('notas', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Llaves en resguardo',
            },
        ),
        migrations.CreateModel(
            name='MotivoIngresoUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=20)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Motivos de ingresos',
            },
        ),
        migrations.CreateModel(
            name='MotivoVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='RH, Proveedor, etc', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperadorPesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombres y Apellidos', max_length=50, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Operadores de camiones pesados',
            },
        ),
        migrations.CreateModel(
            name='SolicitantesUtilitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombres y Apellidos', max_length=50, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Autorizados para pedir utilitarios',
            },
        ),
        migrations.CreateModel(
            name='VehiculoLigero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numeroeconomico', models.CharField(help_text='Numero de la unidad de Vehiculo', max_length=5, unique=True)),
                ('placas', models.CharField(help_text='placas sin guiones', max_length=7, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('notas', models.CharField(max_length=100)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.SolicitantesUtilitario')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos Ligeros',
            },
        ),
        migrations.CreateModel(
            name='VehiculoPesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numeroeconomico', models.CharField(help_text='Numero de la unidad de Vehiculo', max_length=5, unique=True)),
                ('placas', models.CharField(help_text='placas sin guiones', max_length=7, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('notas', models.CharField(max_length=100)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos Pesados',
            },
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('visitaa', models.CharField(max_length=50)),
                ('placas', models.CharField(help_text='placas sin guiones', max_length=7, unique=True)),
                ('temperatura', models.FloatField()),
                ('horasalida', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.MotivoVisita')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Si es proveedor, selecciona aquí', null=True, on_delete=django.db.models.deletion.PROTECT, to='cmp.Proveedor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='empresad',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='uc',
        ),
        migrations.DeleteModel(
            name='AutorizadoUtilitario',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.AddField(
            model_name='llavesenresguardo',
            name='recibo',
            field=models.ForeignKey(help_text='Nombre de quien se recibe las llaves', on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado'),
        ),
        migrations.AddField(
            model_name='llavesenresguardo',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llavesenresguardo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado'),
        ),
        migrations.AddField(
            model_name='ingresounidadpesada',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado'),
        ),
        migrations.AddField(
            model_name='ingresounidadpesada',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresounidadpesada',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado'),
        ),
        migrations.AddField(
            model_name='cargadeurea',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.OperadorPesado'),
        ),
        migrations.AddField(
            model_name='cargadeurea',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargadeurea',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado'),
        ),
        migrations.AddField(
            model_name='cargadediesel',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.DestinosClientes'),
        ),
        migrations.AddField(
            model_name='cargadediesel',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargadediesel',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bita.VehiculoPesado'),
        ),
    ]
