# Generated by Django 2.2.13 on 2022-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bita', '0007_auto_20220422_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='descargadediesel',
            name='residual',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
