# Generated by Django 2.2.13 on 2022-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bita', '0009_auto_20220424_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='descargadediesel',
            name='litrosenbomba',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
