# Generated by Django 2.2.13 on 2022-04-28 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bita', '0010_descargadediesel_litrosenbomba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargadediesel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Pedido', unique=True),
        ),
    ]
