# Generated by Django 2.2.13 on 2022-04-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bita', '0012_auto_20220428_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargadediesel',
            name='litrosenbomba',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descargadediesel',
            name='residual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
