# Generated by Django 2.2.13 on 2022-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bita', '0014_auto_20220505_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoingresounidad',
            name='horasalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
