# Generated by Django 2.2.13 on 2022-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bita', '0016_auto_20220508_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresounidadpesada',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
