# Generated by Django 3.2 on 2023-03-16 20:11

import apps.administration.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', apps.administration.models.CustomUserManager()),
            ],
        ),
    ]
