# Generated by Django 3.2 on 2023-03-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductmodel',
            name='description',
            field=models.CharField(blank=True, help_text='Breve descripción de la categoría que indique su propósito', max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoryproductmodel',
            name='name',
            field=models.CharField(help_text='Nombre de la categoría a la que pertenecerá el producto', max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
