# Generated by Django 3.2 on 2023-03-09 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre del municipio (Ej. Zapopan, Tlaquepaque, etc.)', max_length=50, verbose_name='Nombre del municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'address_municipality',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ingresa el nombre del estado de la república (Ej. Jalisco, Veracruz, etc.)', max_length=50, unique=True, verbose_name='Nombre del estado')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statemodel_user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statemodel_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'address_state',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la colonia (Ej. San Juan de Dios, San Pedro, etc.)', max_length=50, verbose_name='Nombre de la colonia')),
                ('postal_code', models.CharField(default=10000, help_text='Código postal de la colonia (Ej. 45000, 45100, etc.)', max_length=5, verbose_name='Código postal')),
                ('municipality', models.ForeignKey(help_text='Municipio al que pertenece la colonia', on_delete=django.db.models.deletion.PROTECT, to='address.municipalitymodel', verbose_name='Municipio')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoodmodel_user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoodmodel_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
                'db_table': 'address_neighborhood',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='municipalitymodel',
            name='state',
            field=models.ForeignKey(help_text='Estado al que pertenece el municipio(Ej. Jalisco, Veracruz, etc.)', on_delete=django.db.models.deletion.PROTECT, to='address.statemodel', verbose_name='Estado de la república'),
        ),
        migrations.AddField(
            model_name='municipalitymodel',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalitymodel_user_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='municipalitymodel',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalitymodel_user_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(help_text='Calle (Ej. 5 de Mayo, Hidalgo, etc.)', max_length=50, verbose_name='Calle')),
                ('number_ext', models.CharField(help_text='Número exterior (Ej. 123, 456, etc.)', max_length=10, verbose_name='Número exterior')),
                ('number_int', models.CharField(blank=True, help_text='Número interior (Ej. 1, 2, etc.)', max_length=10, null=True, verbose_name='Número interior')),
                ('reference', models.CharField(blank=True, help_text='Referencia (Ej. Entre calles, a 50 metros de, etc.)', max_length=50, null=True, verbose_name='Referencia')),
                ('neighborhood', models.ForeignKey(help_text='Colonia a la que pertenece la dirección', on_delete=django.db.models.deletion.PROTECT, to='address.neighborhoodmodel', verbose_name='Colonia')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressmodel_user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressmodel_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'address_address',
                'ordering': ['street'],
            },
        ),
    ]
