# Generated by Django 3.2 on 2023-03-13 17:12

from django.db import migrations
from apps.address.utils.Sepomex.inserts.funcion_inserts import insert_data

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    def insert_data_sepomex(apps, schema_editor):
        insert_data()


    operations = [
        migrations.RunPython(insert_data_sepomex),
    ]
