# Generated by Django 3.2 on 2023-03-13 17:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(help_text='Razón social del cliente (Ej. Transportes S.A. de C.V.)', max_length=50, unique=True, verbose_name='Razón social')),
                ('rfc', models.CharField(help_text='RFC del cliente (Ej. TASA800101XXX)', max_length=13, unique=True, verbose_name='RFC')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del cliente (Opcional)', max_length=50, null=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono del cliente (Opcional)', max_length=10, null=True, verbose_name='Teléfono')),
                ('first_name', models.CharField(help_text='Nombre del cliente o responsable', max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido paterno del cliente o responsable', max_length=50, verbose_name='Apellido paterno')),
                ('last_name_mother', models.CharField(blank=True, help_text='Apellido materno del cliente o responsable (Opcional)', max_length=50, null=True, verbose_name='Apellido materno')),
                ('address', models.ManyToManyField(blank=True, help_text='Dirección del cliente (Opcional)', to='address.AddressModel', verbose_name='Dirección')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientmodel_user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientmodel_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients_client',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text='Descripción del credito (Ej. Credito para cliente de X empresa)', max_length=100, verbose_name='Descripción')),
                ('amount', models.FloatField(default=0, help_text='Monto máximo del crédito( Ej. 100,000)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Monto del crédito')),
                ('limit_date', models.DateField(blank=True, help_text='Fecha límite para el pago del crédito (Opcional)', null=True, verbose_name='Fecha límite')),
                ('client', models.ForeignKey(help_text='Cliente al que pertenece el crédito', on_delete=django.db.models.deletion.PROTECT, related_name='credit_set', to='clients.clientmodel', verbose_name='Cliente')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditmodel_user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditmodel_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
                'db_table': 'clients_credit',
                'ordering': ['client'],
            },
        ),
    ]
